(defun ch-add ()
  (interactive)
  (goto-char (point-min))
  (open-line 1)
  (insert "-------------------------------------------------------------------\n")
  (open-line 1)
  (insert (shell-command-to-string "date | tr -d '\n'"))
  (insert " - Miroslav Franc <mfranc@suse.cz>\n\n")
  (insert "- Update version ")
  (insert (shell-command-to-string "grep Version: suse-get-maintainers.spec | awk '{print $2}'"))
  (insert "  * "))
